[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0ARGnu0YzVT-MhYUvxBg2ZJUc0CpyLtvPbSVNthr6KNkO1p1ws9bZyQ5LPgLlCadVj7_bAvHnmA-d_6WHoCEdRaVsnONQpJK8E7hr76whUIDDNZQrc5738Xfmunj9qrI8SDiYyiUoQc4cQDRYu3WUijg3POQ-ZIMZsKw9WIomoe48GovMaI2WTeY8A2XvEcvcvsUDbY8aCgYKAacSAQ4SFQHGX2MiUw9xcmxpnE45hHGu8jDoOA0206","token_type":"Bearer","refresh_token":"1//0ghAMWJviWDVlCgYIARAAGBASNwF-L9Ir3KAc06mO2-R5kYoXCrFRu_MH053fpOFfjs3sqRe9q0VgxgPVQf1weh3x76wFYsO2iDc","expiry":"2026-08-10T18:26:12.12503298+07:00"}
client_id = 381280101497-aucccrjjaskl709pa5cffp93aso4g5vi.apps.googleusercontent.com
client_secret = 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
