[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AdMD6EjxuAt-CkmEJlNkmdCncIYs6Hh2k8MCnjPPdyeTx7ju6pg1RI5dY2rK6UV0h3C1BL3W0j4SsP8LYw0f8RHbWJHCX7fpB33Cm5VxpHb5w1cSScYd6dPrN_aNp0I3qTM-GOKlGM194ZCiM4pk4Kxu3n91T1G5wuGKYl8DIIvP5ebtFYKJ56CRVt_2epMdCvahPDsaCgYKAY0SAQ4SFQHGX2MiHd9x5r9MmyIgMFbILSeDhQ0206","token_type":"Bearer","refresh_token":"1//0gDDINtjv37Q9CgYIARAAGBASNwF-L9Irsr0Jxv8as0_hFUJlVtV2HorCrqq5gZjnYAIK1lRdCROSP_HMBbucqLiYRwcgqPA-MlI","expiry":"2026-09-14T10:20:23.2880672+07:00"}
client_id = 381280101497-aucccrjjaskl709pa5cffp93aso4g5vi.apps.googleusercontent.com
client_secret = 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

